language:
  - swift
osx_image: xcode11.1
script:
  - xcodebuild -scheme TestApp -workspace TestApp.xcodeproj/project.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.1'

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 121d334f-bb07-446c-a1ae-9f0072910e2b
